### ISSUE TITLE
Panic coming from tetra::audio::AudioContext::new

### ISSUE THREAD

**Issue by makoConstruct** [VladimirMarkelov/unblocked#3]
```
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /home/mako/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.9.0/src/engine.rs:145:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: rodio::engine::new_output_stream
   4: tetra::audio::AudioContext::new
   5: tetra::ContextBuilder::build
   6: unblock_it::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by VladimirMarkelov** [comment]
Just pushed to the master branch: 

1. tetra `0.2` -> `0.7`. It may help.
2. Also, just in case, I disabled `audio` feature of Tetra - the game does not play any sound anyway. 

But I cannot test it: on my machine both old and new versions work without any issue
